import type { ContractEntry } from '@/domains/contracts/contract.types';

export const contractEntries: ContractEntry[] = [
  {
    id: 'contract-mannshire-catacumbas',
    title: 'Limpieza de catacumbas en Mannshire',
    issuer: 'Administrador local',
    region: 'Mannshire',
    locationLabel: 'Cripta del sendero este',
    dungeonType: 'catacumbas',
    status: 'disponible',
    priority: 'alta',
    dangerTier: 'medio',
    dangerScore: 3,
    rewardGold: 1200,
    rewardNotes: 'Buen retorno para una run de aprendizaje controlado.',
    explanationEs:
      'Contrato ideal para practicar una preparacion segura: consumibles claros, riesgos previsibles y salida razonablemente corta.',
    tacticalSummary: 'Llevar antiveneno ligero, control de desgaste y margen para retirada limpia.',
    recommendedPresetId: 'preset-seguro-mannshire',
    recommendedSupplies: ['Vendas x4', 'Pomada curativa x2', 'Antidoto x1', 'Comida seca x2'],
    enemyTags: ['No-muertos', 'Dano sostenido', 'Pasillos estrechos'],
  },
  {
    id: 'contract-osbrook-bandidos',
    title: 'Campamento de bandidos cerca de Osbrook',
    issuer: 'Capitan de la guardia',
    region: 'Osbrook',
    locationLabel: 'Bosque norte de la cantera',
    dungeonType: 'fortin',
    status: 'seguimiento',
    priority: 'media',
    dangerTier: 'bajo',
    dangerScore: 2,
    rewardGold: 850,
    rewardNotes: 'Contrato rentable para runs cortas de abastecimiento.',
    explanationEs:
      'Buena opcion para builds cuerpo a cuerpo que quieran mantener ritmo de farmeo sin forzar demasiados consumibles.',
    tacticalSummary: 'Controlar inventario, reservar herramientas y castigar grupos pequenos con calma.',
    recommendedPresetId: 'preset-seguro-mannshire',
    recommendedSupplies: ['Vendas x2', 'Agua x1', 'Ganzuas x2', 'Kit de reparacion x1'],
    enemyTags: ['Humanos', 'Botin ligero', 'Exploracion comoda'],
  },
  {
    id: 'contract-brynn-cripta',
    title: 'Cripta antigua en las afueras de Brynn',
    issuer: 'Escribano de Brynn',
    region: 'Brynn',
    locationLabel: 'Ladera sur del cementerio viejo',
    dungeonType: 'cripta',
    status: 'disponible',
    priority: 'alta',
    dangerTier: 'alto',
    dangerScore: 4,
    rewardGold: 1850,
    rewardNotes: 'Mayor recompensa, pero exige una preparacion menos improvisada.',
    explanationEs:
      'Placeholder de mayor riesgo para el MVP. Sirve para pensar luego reglas de scoring, filtros y comparacion entre presets.',
    tacticalSummary: 'Conviene entrar con ruta de escape definida, comida suficiente y control de consumibles raros.',
    recommendedPresetId: 'preset-seguro-mannshire',
    recommendedSupplies: ['Vendajes x5', 'Hierbas x2', 'Licor fuerte x1', 'Antitoxina x1'],
    enemyTags: ['No-muertos', 'Picos de dano', 'Run larga'],
  },
];

