import type { ContractEntry } from '@/domains/contracts/contract.types';

export const contractEntries: ContractEntry[] = [
  {
    id: 'contract-mannshire-catacumbas',
    title: 'Limpieza de catacumbas en Mannshire',
    issuer: 'Administrador local',
    region: 'Mannshire',
    locationLabel: 'Cripta del sendero este',
    dungeonType: 'catacumbas',
    status: 'disponible',
    priority: 'alta',
    dangerTier: 'medio',
    dangerScore: 3,
    rewardGold: 1200,
    rewardNotes: 'Buen retorno para una run de aprendizaje controlado.',
    shortDescription: 'Una salida relativamente estable para practicar preparacion, ritmo y retirada limpia.',
    explanationEs:
      'Contrato ideal para practicar una preparacion segura: consumibles claros, riesgos previsibles y salida razonablemente corta.',
    detailedExplanationEs:
      'Este contrato funciona muy bien como guia para el jugador que aun no quiere improvisar demasiado. La ruta no suele castigar por sorpresa, pero si entra sin control de curacion el desgaste puede volverse frustrante. Conviene pensar la run como una excursion ordenada: entrar, asegurar progreso, no vaciar inventario demasiado pronto y salir antes de que el costo de sostener la pelea supere la recompensa.',
    tacticalSummary: 'Llevar antiveneno ligero, control de desgaste y margen para retirada limpia.',
    suggestedSteps: [
      'Revisar durabilidad de arma y escudo antes de salir.',
      'Entrar con una primera tanda de curacion ya separada en el inventario.',
      'Limpiar la primera zona antes de comprometerse con salas mas profundas.',
      'Salir si el consumo de vendas supera lo planeado demasiado pronto.',
    ],
    expectationsInside: [
      'Pasillos estrechos y peleas de ritmo lento.',
      'No-muertos con desgaste acumulado mas que burst inmediato.',
      'Botin decente, pero no espectacular si te alargas demasiado.',
    ],
    commonMistakes: [
      'Entrar sin huecos libres para botin valioso.',
      'Gastar demasiada curacion en los primeros encuentros.',
      'Insistir cuando la run ya dejo de ser rentable.',
    ],
    personalNotes: 'Buena opcion para una sesion corta si quiero algo predecible.',
    recommendedPresetId: 'preset-seguro-mannshire',
    recommendedSupplies: ['Vendas x4', 'Pomada curativa x2', 'Antidoto x1', 'Comida seca x2'],
    enemyTags: ['No-muertos', 'Dano sostenido', 'Pasillos estrechos'],
  },
  {
    id: 'contract-osbrook-bandidos',
    title: 'Campamento de bandidos cerca de Osbrook',
    issuer: 'Capitan de la guardia',
    region: 'Osbrook',
    locationLabel: 'Bosque norte de la cantera',
    dungeonType: 'fortin',
    status: 'seguimiento',
    priority: 'media',
    dangerTier: 'bajo',
    dangerScore: 2,
    rewardGold: 850,
    rewardNotes: 'Contrato rentable para runs cortas de abastecimiento.',
    shortDescription: 'Una guia amigable para farmear con menos riesgo y buen control del inventario.',
    explanationEs:
      'Buena opcion para builds cuerpo a cuerpo que quieran mantener ritmo de farmeo sin forzar demasiados consumibles.',
    detailedExplanationEs:
      'Este contrato sirve para recordar que no todas las runs tienen que sentirse tensas para ser utiles. La recompensa es razonable, el trayecto no suele exigir una preparacion extravagante y deja margen para volver pronto a vender. Es una buena salida para entrenar decisiones simples: cuando seguir, cuando cortar y cuanto espacio dejar para botin ligero que realmente compense.',
    tacticalSummary: 'Controlar inventario, reservar herramientas y castigar grupos pequenos con calma.',
    suggestedSteps: [
      'Salir con espacio suficiente para loot ligero y herramientas.',
      'Priorizar enemigos aislados antes de abrir mas lineas de combate.',
      'Revisar cofres y rutas secundarias solo si el gasto sigue bajo.',
    ],
    expectationsInside: [
      'Humanos con presion moderada y loot util para vender.',
      'Exploracion relativamente comoda comparada con dungeons cerradas.',
      'Riesgo bajo si mantienes orden en la ruta.',
    ],
    commonMistakes: [
      'Sobrellenar el inventario demasiado pronto.',
      'Subestimar grupos medianos por ir con exceso de confianza.',
      'Gastar herramientas en rutas con poco retorno.',
    ],
    personalNotes: 'Contrato comodo para recuperar economia entre salidas pesadas.',
    recommendedPresetId: 'preset-seguro-mannshire',
    recommendedSupplies: ['Vendas x2', 'Agua x1', 'Ganzuas x2', 'Kit de reparacion x1'],
    enemyTags: ['Humanos', 'Botin ligero', 'Exploracion comoda'],
  },
  {
    id: 'contract-brynn-cripta',
    title: 'Cripta antigua en las afueras de Brynn',
    issuer: 'Escribano de Brynn',
    region: 'Brynn',
    locationLabel: 'Ladera sur del cementerio viejo',
    dungeonType: 'cripta',
    status: 'disponible',
    priority: 'alta',
    dangerTier: 'alto',
    dangerScore: 4,
    rewardGold: 1850,
    rewardNotes: 'Mayor recompensa, pero exige una preparacion menos improvisada.',
    shortDescription: 'Contrato mas exigente para cuando ya quieres una salida con recompensa alta y tension real.',
    explanationEs:
      'Placeholder de mayor riesgo para el MVP. Sirve para pensar luego reglas de scoring, filtros y comparacion entre presets.',
    detailedExplanationEs:
      'La cripta de Brynn representa el tipo de contrato que mas se beneficia de una guia clara. La recompensa invita a entrar, pero la run se puede torcer rapido si el jugador la trata como una salida normal. Aqui importa mucho mas la autonomia, la paciencia y la decision de no forzar una sala extra cuando el estado de la build ya no acompana. Si se aborda con cabeza, puede ser muy rentable; si se improvisa, suele sentirse cara.',
    tacticalSummary: 'Conviene entrar con ruta de escape definida, comida suficiente y control de consumibles raros.',
    suggestedSteps: [
      'Comprar y ordenar consumibles antes de salir de Brynn.',
      'Definir una condicion clara para retirada antes de entrar.',
      'Asegurar la primera parte de la cripta sin gastar recursos especiales demasiado pronto.',
      'Volver si la run exige mas curacion de la prevista.',
    ],
    expectationsInside: [
      'No-muertos con picos de dano y combate mas largo.',
      'Mayor presion sobre curacion, energia y durabilidad.',
      'Mejor recompensa si logras sostener una ruta ordenada.',
    ],
    commonMistakes: [
      'Entrar sin plan de escape.',
      'Usar consumibles raros en encuentros faciles.',
      'Confundir una run posible con una run rentable.',
    ],
    personalNotes: 'No entrar cansado ni con la mochila medio llena.',
    recommendedPresetId: 'preset-seguro-mannshire',
    recommendedSupplies: ['Vendajes x5', 'Hierbas x2', 'Licor fuerte x1', 'Antitoxina x1'],
    enemyTags: ['No-muertos', 'Picos de dano', 'Run larga'],
  },
];
